### ISSUE TITLE
install-peerdeps fails when installing package from github, local directory, or linked package

### ISSUE THREAD

**Issue by tomprats** [nathanhleung/install-peerdeps#44]
When installing a package, npm lets install in [these ways](https://docs.npmjs.com/cli/install):

```
npm install <git repo url>
npm install <folder>
```

Would this package be interested in supporting similar syntax? Or even adding new flags?

**Comment by nathanhleung** [comment]
As of this moment, the package pulls peer dependency information from the official registry based on the `package.json` file. Supporting this syntax would require a rework of the internals (i.e. install the target package first, then read `package.json`, rather than doing it all in one step).

While this is definitely a good feature to support, there are other bugs and issues that are higher priority at the current time. I will keep this issue open for future reference but it's not something this package is looking to support right now.

**Comment by tomprats** [comment]
Thanks for taking a look and getting back to me so quickly @nathanhleung. I appreciate your hard work and your package already has helped a ton!

**Comment by nathanhleung** [comment]
@tomprats @AquiGorka (#42) I've realized your issues deal with similar underlying problems so I've merged them here. I'll keep this issue open for further discussion of this feature and to keep it on the roadmap; if others are also facing this problem I will prioritize it.

**Comment by nathanhleung** [comment]
Thank you for your patience -- resolved by #51
